### ISSUE TITLE
License question 

### ISSUE THREAD

**Issue by TheLeonsver1** [rune-rs/rune#266]
Hello, I'll start by saying that I'm not a lawyer and am not knowledgable about this domain,
but your license in 0.8 doesn't have a year and a copyright owner.
I don't know if it's a legal issue, but I thought it might be worth mentioning because I didn't find any mention of this in any issue or pr...

**Comment by udoprog** [comment]
The license is specified in the cargo manifest. It's dual licensed under MIT/Apache 2.0 applies to all code files of the project unless otherwise specified.

If you go [here for Rune 0.8.0](https://crates.io/crates/rune/0.8.0) you can see the license to the right, under `Metadata`. It is required to specify this when uploading to crates.io

**Comment by TheLeonsver1** [comment]
hmm alright, thank you :). 
btw, the last release tag here is `0.8` and on crates.io you are in version `0.9` already so it should probably be updated no?
