### ISSUE TITLE
Support for Bash script invocation

### ISSUE THREAD

**Issue by InverMN** [rune-rs/rune#270]
Hello there! There is no real support for creating executable files with #!/bin in Rune?

For example the code below:
```rust
#!/bin/rune run

pub fn main() {
    println!("Hello Rune!");
}
```

when invoked returns Rune error:
```
error: parse error
   ┌─ ./rune-script.rn:1:3
   │
 1 │ #!/bin/rune run
   │   ^ expected An open bracket `[`., but got `/`
```

Without that feature it's kinda more trickier to write scripts in Rune

**Comment by tgolsson** [comment]
Hello @InverMN! There's a slight trick you can use here to work around this limitation:

```
//bin/rune run "$0" && exit

pub fn main() {
    println!("Hello Rune!");
}
```

This makes it execute the file as a bash script (or whichever interpreter you use). The first line forwards the file directly to rune, which executes the command. The important step here is the `&& exit`, which prevents the shell from ever reading the *rest of the file*. Since this is a comment block (hence double-slash, even though the path only needs one) Rune dutifully ignores this and runs the file. 

Hope that helps!

**Comment by udoprog** [comment]
It's an interesting workaround. All though I'm re-opening this, cause it would still be nice to support filtering out the shebang on `rune run` to better support this.
