### ISSUE TITLE
Make derive macros work outside of `rune`

### ISSUE THREAD

**Issue by ModProg** [rune-rs/rune#530]
Make derive macros work outside rune such as derive(Parse). To do this one can use either https://docs.rs/proc-macro-crate/latest/proc_macro_crate/ directly or a more complicated approach like here: https://github.com/khonsulabs/bonsaidb/blob/448db4d32ea065aa39b1c4731c0e5b9d5ffce83b/crates/bonsaidb-macros/src/lib.rs#L35-L61 to get more control about it.

**Comment by udoprog** [comment]
From #531, what is the specific problem you're having?

**Comment by udoprog** [comment]
Ah, is it that the `Parse`, `Spanned`, ... macros use `crate::` as a prefix? This can be fixed by:
* Changing the context to now use the `with_crate` constructor - then it will use `rune::` instead.
* Re-export `pub(crate) use crate as rune` [in the `ast::prelude`](https://github.com/rune-rs/rune/blob/e5b7a3a1095768b26fa05ec4e2857aba78a019f7/crates/rune/src/ast/prelude.rs#L4).

That should cover the vast majority of uses for those derives.

**Comment by ModProg** [comment]
>     * Changing the context to now use the `with_crate` constructor - then it will use `rune::` instead.

you mean to not use it? because `with_crate` is the issue, it makes the context use `crate::` or do you mean update `with_crate` to use `rune::`?

**Comment by udoprog** [comment]
Right, `s/now/not`!
