### ISSUE TITLE
[Regression] Installing a module with a crate name panics.

### ISSUE THREAD

**Issue by DarkRTA** [rune-rs/rune#560]
When using rune from the main branch,  you can not install a module with a different crate name due to a type hash mismatch. This works fine in 0.12.4.

```rs
use rune::Module;
use rune::Context;
use rune::Any;

#[derive(Any)]
struct X {
    #[rune(get, set)]
    x: i32,
}

impl X {
    fn get_x_squared(&self) -> i32 { 
        self.x * self.x
    }
}

fn module() -> Module {
    let mut m = Module::with_crate("testcrate");
    m.ty::<X>().unwrap();
    m.associated_function("x_squared", X::get_x_squared).unwrap();
    m
}

fn main() {
    let m = module();
    let mut ctx = Context::new();
    ctx.install(m).unwrap(); // panics
}
```
Console Ouput:
``` 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeHashMismatch { type_info: Any(AnyTypeInfo { name: "tmp::X" }), item: ::testcrate::X, hash: Hash(0x55e7ff128005ac8f), item_hash: Hash(0x7c57d5ebc9226f50) }', src/main.rs:27:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by udoprog** [comment]
Hey!

It's not a regression! It's a breaking change introduced in #509.

If you print the error it gives you more guidance on what needs to change. Basically you now need to specify the item a type belongs to as it's being installed, for you that means:

```rust
#[derive(Any)]
#[rune(item = ::testcrate)]
struct X {
    #[rune(get, set)]
    x: i32,
}
```

This change will be included in the release notes for `0.15.x`. It's necessary because we want to stop relying on `TypeId`'s (which is technically unsound). Good timing too, see #550 where the size of a `TypeId` is about to change.

**Comment by DarkRTA** [comment]
i'm going to close this then. thanks

**Comment by udoprog** [comment]
Will do before release. Thank you!
