### ISSUE TITLE
[Documentation] Is it me or is the required step of installing the CLI missing from the documentation?

### ISSUE THREAD

**Issue by ericmorand** [rune-rs/rune#674]
I'm not sure if I'm missing something obvious here - and I probably _am_, but I struggled understanding how to actually execute rune scripts because both the documentation and the book only mention using the following command to execute a script:

```sh
cargo run --bin rune -- run scripts/hello_world.rn
```

On my system, running this command results in a Cargo runtime error:

```sh
error: no bin target named `rune`.
```

I had to search the internet to actually find in the issue tracker a mention about `rune-cli`, which I ended up installing...without success.

Forgive my if I'm missing something obvious: Rust is pretty new to me (I'm still at an early stages of learning the language and its ecosystem) and nothing is obvious to me at the moment.

**Comment by udoprog** [comment]
The given command can be run from within the project. to "build your own" CLI you'd make use of the [modular commandline](https://rune-rs.github.io/posts/rune-0-13-0/#modular-commandline) support since you'd have to install your own context.

To *just* use the default Rune CLI, you can install it through cargo:

```
cargo install rune-cli
```
