### ISSUE TITLE
Can the rune VM be used in a lightweight webassembly module?

### ISSUE THREAD

**Issue by sanity** [rune-rs/rune#692]
I'm working on [Freenet](https://freenet.org/), a large-scale platform for distributed computation.

Freenet relies on lightweight webassembly modules called [contracts](https://docs.freenet.org/components/contracts.html) which we currently compile from Rust, these need to be small so we use `![no_std]` and minimize dependencies.

The problem is that Rust has a significant learning curve, and so I was wondering whether we could use Rune to allow the easy creation of Freenet contracts - which (in Rust) implement the [ContractInterface](https://github.com/freenet/freenet-stdlib/blob/f5597dfd440a0470bcd306ce9f50883b42060a6e/rust/src/contract_interface.rs#L446) trait.

I found #662 so it appears that Rune can work with WebAssembly, but it wasn't clear to me what the [code example](https://github.com/freenet/freenet-stdlib/blob/f5597dfd440a0470bcd306ce9f50883b42060a6e/rust/src/contract_interface.rs#L446) was doing - so I thought I'd ask directly:

Can the Rune VM be used in a lightweight wasm module (with `no_std`) to provide a Rune implementation of the ContractInterface trait?

**Comment by udoprog** [comment]
Hi,

I would say no, from what I can intuit of your definition of "lightweight". But it really depends.

Since Rune will always be a virtual machine running on top of webassembly in contrast to Rust, which *targets* webassembly (code written in Rust directly becomes webassembly instructions) it will never have that low of an overhead. I.e. Rune won't take your scripts and convert them into native webassembly modules.

Rune also requires the use of an allocator. The memory for the virtual machine is allocated explicitly through the system allocator.

> I found https://github.com/rune-rs/rune/issues/662 so it appears that Rune can work with WebAssembly, but it wasn't clear to me what the [code example](https://github.com/freenet/freenet-stdlib/blob/f5597dfd440a0470bcd306ce9f50883b42060a6e/rust/src/contract_interface.rs#L446) was doing - so I thought I'd ask directly:

The code example linked in 662 is a webassembly module which [defines a function that takes a string](https://github.com/rune-rs/rune/blob/main/crates/rune-wasm/src/lib.rs#L378). This string is then compiled as a unit for the rune virtual machine which is compiled for webassembly to execute.

**Comment by sanity** [comment]
Thank you for the reply.

I understand that the Rune VM running on the wasm VM will not be as lightweight as Rust code compiled to wasm directly - my question is more whether the Rune compiler and VM can run on webassembly. I think it can based on the example I found.

Thanks again.
