### ISSUE TITLE
&& operator changes the value of a boolean

### ISSUE THREAD

**Issue by dstoza** [rune-rs/rune#830]
Given the following code:
```rust
pub fn main() {
    let value = true;
    
    if value && false {
    	println!("not seen")
    }
    
    println!("{value}")
}
```

One would expect `true` to be printed, but instead the `&&` operator seems to change the value of `value` to `false`. If instead the condition is changed to `value && true`, `value` doesn't seem to change.

Playground link [here](https://rune-rs.github.io/play/?c=cHViIGZuIG1haW4oKSB7CiAgICBsZXQgdmFsdWUgPSB0cnVlOwogICAgCiAgICBpZiB2YWx1ZSAmJiBmYWxzZSB7CiAgICAJcHJpbnRsbiEoIm5vdCBzZWVuIikKICAgIH0KICAgIAogICAgcHJpbnRsbiEoInt2YWx1ZX0iKQp9Cg%3D%3D)

**Comment by udoprog** [comment]
Thanks for the report!

This is a bug introduced by #733

We can see it incorrectly reusing the allocated slot for `value` (if you we enable `instructions` on the playground):

```
# instruction
fn main() (0x1c69d5964e831fc1):
  0000 = allocate size=3
  0001 = store value=true, out=keep(0)
  entry:2:17-21: let value = true;
  0002 = jump-if-not cond=0, jump=4 // label:conditional_end_4 (4)
  entry:4:8-13: if value && false {
  0003 = store value=false, out=keep(0)
  entry:4:17-22: if value && false {
```

This is probably caused by an incorrect optimization [here](https://github.com/rune-rs/rune/blob/main/crates/rune/src/compile/v1/assemble.rs#L1525), whereas the needs for the left hand side is re-used by the temporary in the right hand side operator, causing it to be assigned the same slot.

**Comment by dstoza** [comment]
Thanks for the quick fix!
